In [5]:
import os
from pathlib import Path
import pickle
import numpy as np
import pandas as pd

In [1]:
def load_data(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)

In [6]:
data_root = r"C:/Users/hayashi/doutorado/mac6958--dados-redes/webrtc"
data_file = Path(data_root, 'data/processed/facial-1001-normalized.pkl')

In [7]:
data = load_data(data_file)

In [8]:
data[0]

{'user_id': -1.647508942095828,
 'test_condition': 0.4629100498862757,
 'delay': 1.0690449676496976,
 'jitter': 1.224744871391589,
 'packet_loss_rate': 0.0,
 'features': array([[ 0.200067, -0.033075, -0.979224, ...,  1.      ,  0.      ,
          0.      ],
        [ 0.203814, -0.040347, -0.978178, ...,  1.      ,  0.      ,
          0.      ],
        [ 0.203665, -0.042064, -0.978137, ...,  0.      ,  0.      ,
          0.      ],
        ...,
        [-0.020206,  0.302458, -0.952948, ...,  0.      ,  0.      ,
          0.      ],
        [-0.015582,  0.300056, -0.953794, ...,  0.      ,  0.      ,
          0.      ],
        [-0.021239,  0.304443, -0.952294, ...,  1.      ,  0.      ,
          0.      ]])}

In [10]:
data[0]['features'].shape

(3676, 323)

In [16]:
d= data[0]
# get one label as vector
y = np.array([value for key, value in d.items() if key != 'features'])
y

array([-1.64750894,  0.46291005,  1.06904497,  1.22474487,  0.        ])

In [17]:
y.shape

(5,)

In [23]:
np.tile(y, (2,2,2))

array([[[-1.64750894,  0.46291005,  1.06904497,  1.22474487,
          0.        , -1.64750894,  0.46291005,  1.06904497,
          1.22474487,  0.        ],
        [-1.64750894,  0.46291005,  1.06904497,  1.22474487,
          0.        , -1.64750894,  0.46291005,  1.06904497,
          1.22474487,  0.        ]],

       [[-1.64750894,  0.46291005,  1.06904497,  1.22474487,
          0.        , -1.64750894,  0.46291005,  1.06904497,
          1.22474487,  0.        ],
        [-1.64750894,  0.46291005,  1.06904497,  1.22474487,
          0.        , -1.64750894,  0.46291005,  1.06904497,
          1.22474487,  0.        ]]])

In [21]:
np.tile(y, (2,2))

array([[-1.64750894,  0.46291005,  1.06904497,  1.22474487,  0.        ,
        -1.64750894,  0.46291005,  1.06904497,  1.22474487,  0.        ],
       [-1.64750894,  0.46291005,  1.06904497,  1.22474487,  0.        ,
        -1.64750894,  0.46291005,  1.06904497,  1.22474487,  0.        ]])

In [30]:
np.tile([[1,2],[3,4]], (3,))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [32]:
np.tile([[1,2],[3,4]], (3,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [33]:
y.shape

(5,)

In [35]:
Y = np.tile(y,(120,1))

In [36]:
Y.shape

(120, 5)

In [37]:
x = data[0]['features']

In [38]:
x.shape

(3676, 323)

In [50]:
int(x.shape[0]/30)*30

3660

In [49]:
int(x.shape[0]/30)

122

In [43]:
x.shape[0]/30

122.53333333333333

In [48]:
int(1.6)

1

In [51]:
size = int(x.shape[0]/30)*30
x1 = x[:size]

In [52]:
x1.shape

(3660, 323)

In [53]:
x2 = x1.reshape((-1,30,323))

In [54]:
x2.shape

(122, 30, 323)

In [56]:
for dd in data:
    print(dd['features'].shape)

(3676, 323)
(3676, 323)
(3665, 323)
(3633, 323)
(3666, 323)
(205, 323)
(3662, 323)
(3666, 323)
(3666, 323)
(3677, 323)
(3665, 323)
(3676, 323)
(3665, 323)
(3665, 323)
(3665, 323)
(3700, 323)
(3705, 323)
(741, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3676, 323)
(3666, 323)
(3662, 323)
(3665, 323)
(3673, 323)
(3665, 323)
(3666, 323)
(3677, 323)
(3676, 323)
(3665, 323)
(3676, 323)
(3665, 323)
(3676, 323)
(3665, 323)
(3677, 323)
(3676, 323)
(3666, 323)
(3666, 323)
(3665, 323)
(530, 323)
(3662, 323)
(3677, 323)
(3676, 323)
(3665, 323)
(3666, 323)
(3676, 323)
(3665, 323)
(3666, 323)
(3664, 323)
(3666, 323)
(3716, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3704, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3701, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 323)
(3705, 

In [59]:
def split_and_reshape(dd):
    # given dict, return (-1,30,323), (-1,5)

    # for x, split in seq size of 30
    x = dd['features']    # (-1,323)
    seq_size = int(x.shape[0]/30)
    x = x[:seq_size*30]
    assert x.shape[1]== 323, "Expected shape of (-1,323) for feature"
    x = x.reshape((-1,30,323))

    # for y, replicate of each sequence
    y = np.array([value for key, value in d.items() if key != 'features'])  # (5,)
    y = np.tile(y, (seq_size,1))

    return x, y    
    
def convert_to_seq(data):
    x_list, y_list = [], []
    for d in data:
        x,y = split_and_reshape(d)   # return (-1,30,323), (-1,5)
        x_list.append(x)
        y_list.append(y)

    # append along the first dimension
    X = np.concatenate(x_list, axis=0)
    Y = np.concatenate(y_list, axis=0)
    return X, Y

In [ ]:
X, Y = convert_to_seq(data)    # return (-1,30,323), (-1,5)

In [61]:
x, y = split_and_reshape(data[0])

In [62]:
x.shape, y.shape

((122, 30, 323), (122, 5))

In [65]:
X, Y = convert_to_seq(data[0:2])

In [66]:
X.shape, Y.shape

((244, 30, 323), (244, 5))

In [67]:
X, Y = convert_to_seq(data)

In [68]:
X.shape, Y.shape

((34880, 30, 323), (34880, 5))

In [70]:
seq_data_file = Path(data_root, 'data/processed/facial-1007-sequential.pkl')

In [71]:
with open(seq_data_file, 'wb') as file:
    pickle.dump((X,Y), file)